language: cpp
compiler:
- clang
os:
- osx
before_install:
- echo $LANG
- echo $LC_ALL
- brew update && brew install cmake
- mkdir build
- cd build
- cmake -DCMAKE_CXX_COMPILER=clang++ ../src
script:
- make